service: serverless-restful-crud

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  create:
    handler: src/handlers/create.create
    events:
      - httpApi:
          path: /users/create
          method: POST
  find:
    handler: src/handlers/find.find
    events:
      - httpApi:
          path: /users/find
          method: GET
